# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_notepad(object):
    def setupUi(self, notepad):
        notepad.setObjectName(_fromUtf8("notepad"))
        notepad.resize(513, 360)
        self.MainWindow_2 = QtGui.QWidget(notepad)
        self.MainWindow_2.setObjectName(_fromUtf8("MainWindow_2"))
        self.led = LedWidget(self.MainWindow_2)
        self.led.setGeometry(QtCore.QRect(21, 56, 60, 171))
        self.led.setObjectName(_fromUtf8("led"))
        self.verticalLayout = QtGui.QVBoxLayout(self.led)
        self.verticalLayout.setMargin(11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.startBtn = QtGui.QPushButton(self.MainWindow_2)
        self.startBtn.setGeometry(QtCore.QRect(10, -1, 81, 27))
        self.startBtn.setObjectName(_fromUtf8("startBtn"))
        self.stopBtn = QtGui.QPushButton(self.MainWindow_2)
        self.stopBtn.setGeometry(QtCore.QRect(10, 27, 81, 27))
        self.stopBtn.setObjectName(_fromUtf8("stopBtn"))
        self.label_9 = QtGui.QLabel(self.MainWindow_2)
        self.label_9.setGeometry(QtCore.QRect(90, 2, 61, 20))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.textEdit_T1 = QtGui.QTextEdit(self.MainWindow_2)
        self.textEdit_T1.setGeometry(QtCore.QRect(330, 240, 71, 31))
        self.textEdit_T1.setObjectName(_fromUtf8("textEdit_T1"))
        self.textEdit_T2 = QtGui.QTextEdit(self.MainWindow_2)
        self.textEdit_T2.setGeometry(QtCore.QRect(330, 280, 71, 31))
        self.textEdit_T2.setObjectName(_fromUtf8("textEdit_T2"))
        self.PAtempLabel = QtGui.QLabel(self.MainWindow_2)
        self.PAtempLabel.setGeometry(QtCore.QRect(401, 286, 91, 20))
        self.PAtempLabel.setObjectName(_fromUtf8("PAtempLabel"))
        self.label_5 = QtGui.QLabel(self.MainWindow_2)
        self.label_5.setGeometry(QtCore.QRect(403, 250, 101, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.textRawHK = QtGui.QTextEdit(self.MainWindow_2)
        self.textRawHK.setGeometry(QtCore.QRect(170, 0, 341, 31))
        self.textRawHK.setObjectName(_fromUtf8("textRawHK"))
        self.nextModeBtn = QtGui.QPushButton(self.MainWindow_2)
        self.nextModeBtn.setGeometry(QtCore.QRect(410, 190, 91, 27))
        self.nextModeBtn.setObjectName(_fromUtf8("nextModeBtn"))
        self.label_6 = QtGui.QLabel(self.MainWindow_2)
        self.label_6.setGeometry(QtCore.QRect(234, 246, 91, 20))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.textEdit_freq = QtGui.QTextEdit(self.MainWindow_2)
        self.textEdit_freq.setGeometry(QtCore.QRect(160, 240, 71, 31))
        self.textEdit_freq.setObjectName(_fromUtf8("textEdit_freq"))
        self.tuneUpBtn = QtGui.QPushButton(self.MainWindow_2)
        self.tuneUpBtn.setGeometry(QtCore.QRect(160, 270, 51, 27))
        self.tuneUpBtn.setObjectName(_fromUtf8("tuneUpBtn"))
        self.tuneDnBtn = QtGui.QPushButton(self.MainWindow_2)
        self.tuneDnBtn.setGeometry(QtCore.QRect(220, 270, 51, 27))
        self.tuneDnBtn.setObjectName(_fromUtf8("tuneDnBtn"))
        self.layoutWidget = QtGui.QWidget(self.MainWindow_2)
        self.layoutWidget.setGeometry(QtCore.QRect(400, 70, 112, 122))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setMargin(11)
        self.verticalLayout_3.setSpacing(6)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.point_0 = QtGui.QLabel(self.layoutWidget)
        self.point_0.setObjectName(_fromUtf8("point_0"))
        self.verticalLayout_3.addWidget(self.point_0)
        self.point_1 = QtGui.QLabel(self.layoutWidget)
        self.point_1.setObjectName(_fromUtf8("point_1"))
        self.verticalLayout_3.addWidget(self.point_1)
        self.point_2 = QtGui.QLabel(self.layoutWidget)
        self.point_2.setObjectName(_fromUtf8("point_2"))
        self.verticalLayout_3.addWidget(self.point_2)
        self.label_12 = QtGui.QLabel(self.MainWindow_2)
        self.label_12.setGeometry(QtCore.QRect(400, 50, 110, 17))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.powerBtn_1 = QtGui.QPushButton(self.MainWindow_2)
        self.powerBtn_1.setGeometry(QtCore.QRect(70, 60, 21, 21))
        self.powerBtn_1.setText(_fromUtf8(""))
        self.powerBtn_1.setObjectName(_fromUtf8("powerBtn_1"))
        self.powerBtn_2 = QtGui.QPushButton(self.MainWindow_2)
        self.powerBtn_2.setGeometry(QtCore.QRect(70, 80, 21, 21))
        self.powerBtn_2.setText(_fromUtf8(""))
        self.powerBtn_2.setObjectName(_fromUtf8("powerBtn_2"))
        self.powerBtn_3 = QtGui.QPushButton(self.MainWindow_2)
        self.powerBtn_3.setGeometry(QtCore.QRect(70, 100, 21, 21))
        self.powerBtn_3.setText(_fromUtf8(""))
        self.powerBtn_3.setObjectName(_fromUtf8("powerBtn_3"))
        self.powerBtn_4 = QtGui.QPushButton(self.MainWindow_2)
        self.powerBtn_4.setGeometry(QtCore.QRect(70, 120, 21, 21))
        self.powerBtn_4.setText(_fromUtf8(""))
        self.powerBtn_4.setObjectName(_fromUtf8("powerBtn_4"))
        self.powerBtn_5 = QtGui.QPushButton(self.MainWindow_2)
        self.powerBtn_5.setGeometry(QtCore.QRect(70, 140, 21, 21))
        self.powerBtn_5.setText(_fromUtf8(""))
        self.powerBtn_5.setObjectName(_fromUtf8("powerBtn_5"))
        self.powerBtn_6 = QtGui.QPushButton(self.MainWindow_2)
        self.powerBtn_6.setGeometry(QtCore.QRect(70, 160, 21, 21))
        self.powerBtn_6.setText(_fromUtf8(""))
        self.powerBtn_6.setObjectName(_fromUtf8("powerBtn_6"))
        self.powerBtn_7 = QtGui.QPushButton(self.MainWindow_2)
        self.powerBtn_7.setGeometry(QtCore.QRect(70, 180, 21, 21))
        self.powerBtn_7.setText(_fromUtf8(""))
        self.powerBtn_7.setObjectName(_fromUtf8("powerBtn_7"))
        self.powerBtn_8 = QtGui.QPushButton(self.MainWindow_2)
        self.powerBtn_8.setGeometry(QtCore.QRect(70, 200, 21, 21))
        self.powerBtn_8.setText(_fromUtf8(""))
        self.powerBtn_8.setObjectName(_fromUtf8("powerBtn_8"))
        self.rollSlider = QtGui.QSlider(self.MainWindow_2)
        self.rollSlider.setGeometry(QtCore.QRect(330, 60, 61, 29))
        self.rollSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rollSlider.setObjectName(_fromUtf8("rollSlider"))
        self.label_21 = QtGui.QLabel(self.MainWindow_2)
        self.label_21.setGeometry(QtCore.QRect(340, 50, 41, 17))
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.label_22 = QtGui.QLabel(self.MainWindow_2)
        self.label_22.setGeometry(QtCore.QRect(340, 90, 41, 17))
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.pitchSlider = QtGui.QSlider(self.MainWindow_2)
        self.pitchSlider.setGeometry(QtCore.QRect(330, 100, 61, 29))
        self.pitchSlider.setOrientation(QtCore.Qt.Horizontal)
        self.pitchSlider.setObjectName(_fromUtf8("pitchSlider"))
        self.label = QtGui.QLabel(self.MainWindow_2)
        self.label.setGeometry(QtCore.QRect(330, 130, 67, 17))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.MainWindow_2)
        self.label_2.setGeometry(QtCore.QRect(330, 180, 67, 17))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.layoutWidget1 = QtGui.QWidget(self.MainWindow_2)
        self.layoutWidget1.setGeometry(QtCore.QRect(90, 64, 42, 156))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setMargin(11)
        self.verticalLayout_2.setSpacing(6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_18 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_2.addWidget(self.label_18)
        self.label_13 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_2.addWidget(self.label_13)
        self.label_14 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_2.addWidget(self.label_14)
        self.label_19 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_2.addWidget(self.label_19)
        self.label_15 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_2.addWidget(self.label_15)
        self.label_16 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_2.addWidget(self.label_16)
        self.label_20 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_2.addWidget(self.label_20)
        self.label_17 = QtGui.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.verticalLayout_2.addWidget(self.label_17)
        self.textEdit = QtGui.QTextEdit(self.MainWindow_2)
        self.textEdit.setGeometry(QtCore.QRect(0, 240, 151, 91))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.label_23 = QtGui.QLabel(self.MainWindow_2)
        self.label_23.setGeometry(QtCore.QRect(10, 223, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.textEdit_Lon = QtGui.QTextEdit(self.MainWindow_2)
        self.textEdit_Lon.setGeometry(QtCore.QRect(330, 200, 71, 31))
        self.textEdit_Lon.setObjectName(_fromUtf8("textEdit_Lon"))
        self.textEdit_Lat = QtGui.QTextEdit(self.MainWindow_2)
        self.textEdit_Lat.setGeometry(QtCore.QRect(330, 150, 71, 31))
        self.textEdit_Lat.setObjectName(_fromUtf8("textEdit_Lat"))
        notepad.setCentralWidget(self.MainWindow_2)
        self.menuBar = QtGui.QMenuBar(notepad)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 513, 22))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        notepad.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(notepad)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        notepad.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)

        self.retranslateUi(notepad)
        QtCore.QMetaObject.connectSlotsByName(notepad)

    def retranslateUi(self, notepad):
        notepad.setWindowTitle(_translate("notepad", "Phase Shifter GUI", None))
        self.startBtn.setText(_translate("notepad", "Open", None))
        self.stopBtn.setText(_translate("notepad", "Close", None))
        self.label_9.setText(_translate("notepad", "Comm", None))
        self.PAtempLabel.setText(_translate("notepad", "PA Temp (C)", None))
        self.label_5.setText(_translate("notepad", "VCO Temp (C)", None))
        self.nextModeBtn.setText(_translate("notepad", "Next Mode", None))
        self.label_6.setText(_translate("notepad", "VCO (MHz)", None))
        self.tuneUpBtn.setText(_translate("notepad", "Up", None))
        self.tuneDnBtn.setText(_translate("notepad", "Down", None))
        self.point_0.setText(_translate("notepad", "Light House", None))
        self.point_1.setText(_translate("notepad", "Ft. Sumner\n"
"Tracking Station", None))
        self.point_2.setText(_translate("notepad", "Clovis\n"
"Tracking Station", None))
        self.label_12.setText(_translate("notepad", "MODE", None))
        self.label_21.setText(_translate("notepad", "Roll", None))
        self.label_22.setText(_translate("notepad", "Pitch", None))
        self.label.setText(_translate("notepad", "Lat", None))
        self.label_2.setText(_translate("notepad", "Lon", None))
        self.label_18.setText(_translate("notepad", "VCO 5.5", None))
        self.label_13.setText(_translate("notepad", "VCO 15", None))
        self.label_14.setText(_translate("notepad", "PA 1", None))
        self.label_19.setText(_translate("notepad", "PA 2", None))
        self.label_15.setText(_translate("notepad", "MSB", None))
        self.label_16.setText(_translate("notepad", "LSB", None))
        self.label_20.setText(_translate("notepad", "Use CW", None))
        self.label_17.setText(_translate("notepad", "PA 3", None))
        self.label_23.setText(_translate("notepad", "Warnings", None))

from ledwidget import LedWidget
